sudo: required
dist: trusty

install:
    # Install newer version of Docker
    - sudo apt-get purge -y --force-yes docker-engine || true
    - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    - echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
    - sudo apt-get update
    - sudo apt-get install -q -y --no-install-recommends --force-yes docker-engine

script:
    for filename in $(ls */make*.sh); do bash $filename || exit 1; done
