FROM ubuntu:14.04

RUN apt-get update && apt-get install -y --no-install-recommends --force-yes \
        build-essential \
        ca-certificates \
        devscripts \
        equivs \
        git \
        && rm -rf /var/lib/apt/lists/*
